name: extraedmobile
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^13.2.0
  dio: ^5.4.1
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  awesome_dialog: ^3.2.0
  flutter_inappwebview: ^6.0.0
  freezed_annotation: ^2.4.1
  flutter_slidable: ^3.0.1
  bloc: ^8.1.3
  hydrated_bloc: ^9.1.4
  path_provider: ^2.1.2
  meta: ^1.11.0
  get_it: ^7.6.7
  intl: ^0.19.0
  floor: ^1.4.2
  flutter_hooks: ^0.20.5
  retrofit_generator: ^8.1.0
  floor_generator: ^1.4.2
  build_runner: ^2.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
 uses-material-design: true
fonts:
  - family: Muli
    fonts:
      - asset: assets/fonts/muli/Muli.ttf
      - asset: assets/fonts/muli/Muli-Bold.ttf
        weight: 700
      - asset: assets/fonts/muli/Muli-Light.ttf
        weight: 300